### ISSUE TITLE
Verticle button css is backwards

### ISSUE THREAD

**Issue by JustinWehr** [nkovacic/angular-touchspin#10]
The verticle button CSS is backwards for me. As you can see from the screenshot, the button radiuses are in the wrong spot. Also wouldn't the up button need to be created before the down button?

![image](https://cloud.githubusercontent.com/assets/23170975/20713685/421cb6bc-b617-11e6-92c6-cae8850ef22b.png)

![image](https://cloud.githubusercontent.com/assets/23170975/20713664/30b54cb8-b617-11e6-9af6-88de5ea18e78.png)

**Comment by nkovacic** [comment]
Thank you for the bug report. Fixed in [1.4.1](https://github.com/nkovacic/angular-touchspin/releases/tag/1.4.1)
