### ISSUE TITLE
can not update touch spin min max using angular model

### ISSUE THREAD

**Issue by karen-hikesupport** [nkovacic/angular-touchspin#12]
Hi,

we can not update min max property value on input using touch spin 

Regards
karen

**Comment by nkovacic** [comment]
Can you please post an example of the bug to plunkr?

**Comment by bostondevin** [comment]
+1 - if you try and set min / max to a variable it doesn't seem to work

**Comment by nkovacic** [comment]
@bostondevin an example of the bug on plunkr or jsfiddle would be great.

**Comment by bostondevin** [comment]
I'm trying to get this to work on plunkr, not sure what i'm doing wrong...

https://plnkr.co/edit/Tgt4Z0k7Xf0GwUBpV1J5?p=preview

**Comment by bostondevin** [comment]
Hi - I got this working so you can see the issue - it seems to completely ignore the min / max / decimals I set if I do it this way: https://plnkr.co/edit/Tgt4Z0k7Xf0GwUBpV1J5?p=preview

**Comment by nkovacic** [comment]
The example does not work. Please fix it.

**Comment by bostondevin** [comment]
That last link I sent is working for me in the latest Chrome: https://plnkr.co/edit/Tgt4Z0k7Xf0GwUBpV1J5?p=preview

**Comment by nkovacic** [comment]
Options are not assigned to the right attribute. You shoud use the options attribute for them, instead of touch-spin.
All the documentation for using options are in the readme.md

**Comment by bostondevin** [comment]
ok - that worked - thanks! I must've had some old code

**Comment by karen-hikesupport** [comment]
Hi,

https://plnkr.co/edit/ZwGwFyAbExsd1wAMbPvH?p=preview

I have  update the link and it could not work. please fix it.

**Comment by nkovacic** [comment]
@karen-hikesupport you have the same problem as @bostondevin. Please refer to my solution above.

**Comment by nkovacic** [comment]
Going to to close this issue because there is no apparent error.
