### ISSUE TITLE
Speed up incrementing the longer you hold the + / - buttons and keys

### ISSUE THREAD

**Issue by bostondevin** [nkovacic/angular-touchspin#13]
I've seen on similar ui components that as you continue to hold the up / down keys, the time it takes to increment the number gets progressively faster. This is really helpful if you are going from say zero to 1000 - it takes a lot less time to get there. You may have already made this possible and I don't know how to set the option, but if not, is there a way to modify it?

**Comment by bostondevin** [comment]
Here's an implementation of it - http://stackoverflow.com/questions/702165/how-do-i-implement-press-and-hold-button-javascript

**Comment by nkovacic** [comment]
Its implemented for clicking + and - button. I will add the keyboard shortcuts in the next release.

**Comment by nkovacic** [comment]
Implemented also for keyboards shortcuts in [1.4.5](https://github.com/nkovacic/angular-touchspin/releases/tag/1.4.5)
