### ISSUE TITLE
Button click and mouse leave

### ISSUE THREAD

**Issue by Jeancpdamke** [nkovacic/angular-touchspin#14]
If you hold the left mouse button on the touchspin buttons ('+' and '-' or the vertical buttons) and then drag the mouse pointer off the button area, the value of the input will keep increasing (or decreasing), even when you stop pressing the mouse.

The best solution I can think to solve this of is to add a "ng-mouseleave=vm.stopSpin()" into every button tag on the directive html. This way the value will stop changing when you leave the button area.

**Comment by nkovacic** [comment]
Fixed in [1.4.5](https://github.com/nkovacic/angular-touchspin/releases/tag/1.4.5).
The solution was exactly what you described.
