### ISSUE TITLE
Debounce on mouse click

### ISSUE THREAD

**Issue by unluckynelson** [nkovacic/angular-touchspin#15]
Love the touchspin, thanks for great package.
Users are however complaining that the first click always jumps two increments, after that it works fine. The issue is intermittent.
I can confirm that this happens in testing too. When clicking the up arrow once the input would jump from 0 to 2

**Comment by nkovacic** [comment]
Could you please create a plunkr, I have a problem reproducing your issue?

**Comment by nkovacic** [comment]
It was solved here #16
