### ISSUE TITLE
Double counting

### ISSUE THREAD

**Issue by J4si3k** [nkovacic/angular-touchspin#16]
Sometimes when I click + or - the number is incremented or decremented double. This is apparent even after the basic configuration. Just click every 0.5 seconds. Here plunker: http://plnkr.co/edit/8c6WnxtisdQlxFyX8tzm?p=preview

**Comment by niranjan92** [comment]
+1 there should be an option to limit speed of increments.

**Comment by nkovacic** [comment]
An pull request would be very appreciated :)

**Comment by amalfra** [comment]
won't setting ```stepInterval``` option work?

**Comment by niranjan92** [comment]
Hey Thanks @amalfra. adding `stepInterval` worked. 

```
<div touch-spin options="{ 'stepInterval': 1000}" ng-model="dummymodel" type="number" name="test-touch-spin"/>
 ```

**Comment by amalfra** [comment]
@niranjan92 You are welcome! Happy to know that fixed your issue

**Comment by niranjan92** [comment]
@nkovacic i guess you can close the issue now

**Comment by unluckynelson** [comment]
Thanks @nkovacic, Is there any way to set the { 'stepInterval': 1000} globally?

**Comment by nkovacic** [comment]
@unluckynelson its possible! There is a undocumented touchSpinConfig provider that acccepts the same options as the directive and they will be applied globally
