### ISSUE TITLE
Increment/Decrements call two times for vertical buttons.

### ISSUE THREAD

**Issue by imran-khan-9l** [nkovacic/angular-touchspin#20]
TouchSpinController.prototype.startSpinUp = function () {
                
                var _this = this;
                this.checkValue();
                if (this.touchSpinOptions.verticalButtons) {
                    this.decrement(); // **first decrement value here**
                } else {
                    this.increment(); // **first increment value here**
                }
                this.stopSpin(true);
                this.clickStart = Date.now();
                this.timeout = this.$timeout(function () {
                    // if (this.timer) {
                    // 	this.$interval.cancel(this.timer);
                    // }
                    _this.timer = _this.$interval(function () {
                        if (_this.touchSpinOptions.verticalButtons) {
                            _this.decrement(); **// again value decrement here**
                        } else {
                            _this.increment(); **// again value increment here**
                        }
                    }, _this.touchSpinOptions.stepInterval);
                }, this.touchSpinOptions.stepIntervalDelay);
            };

**Comment by nkovacic** [comment]
Noticed that bug is appearing again, will try to fix it in the next release

**Comment by nkovacic** [comment]
Increment/decrement called two times is fixed in version 1.5.0.
