### ISSUE TITLE
Declares to bundle TypeScript types, but those are not published

### ISSUE THREAD

**Issue by ghost** [nkovacic/angular-touchspin#21]
`package.json` includes `"types": "./src/angular-touchspin.d.ts",` but that file is not distributed on npm -- it's in the [`.npmignore`](https://github.com/nkovacic/angular-touchspin/blob/51435a7ed2fc04ba4fcdda0e9f94a3d620c538e4/.npmignore#L18).
It would be nice to have that file included in the distribution so the duplicate typings could be removed from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular-touchspin/index.d.ts).

**Comment by nkovacic** [comment]
Fixed in [1.8.0](https://github.com/nkovacic/angular-touchspin/releases/tag/1.8.0).
