### ISSUE TITLE
iPhone spinner not working

### ISSUE THREAD

**Issue by TravisHiscock** [nkovacic/angular-touchspin#5]
The Bootstrap Touchspin [http://www.virtuosoft.eu/code/bootstrap-touchspin/](url) works fine on an iPhone, if I touch and hold a plus or minus button, the spinner starts spinning.

With angular-touchspin the spinner reacts to click and hold correctly and starts spinning on a browser.
However on an iPhone it does not.  It never spins and only increments the value on releasing the touch.

This is a crucial usability issue

**Comment by nkovacic** [comment]
Touch events are currently not supported. 
A PR would be very welcome :).

**Comment by bostondevin** [comment]
+1

**Comment by nkovacic** [comment]
Added touch events in [1.4.6](https://github.com/nkovacic/angular-touchspin/releases/tag/1.4.6)
