### ISSUE TITLE
Can't display the default value of ng-model ...

### ISSUE THREAD

**Issue by pconihout** [nkovacic/angular-touchspin#9]
Hi,

I have a simple controller with : 
```
$scope.value = 75;
$scope.options = {
        verticalButtons: true,
        decimals: 2,
        max: 100,
        min: 0.1,
        step: 0.1
 }

```

And in my html : 
`<touch-spin ng-model="value" options="options"></touch-spin>`

But the spin display 0.1 (minimum value) instead of 75 ? Any ideas ?

Thx.

**Comment by nkovacic** [comment]
Please make a jsfiddle, so I can look into it

**Comment by pconihout** [comment]
You can have a look here : https://jsfiddle.net/odh7rms4/

**Comment by nkovacic** [comment]
Thansk for the bug report.
Fixed it with https://github.com/nkovacic/angular-touchspin/releases/tag/1.4.0
